


fun main(args: str[]) -> num {
   disp("Hello, World!");

   emit 0;
}


class Person {
   name: str;
   age: num;

   fun init(name: str, age: num) -> self {
      self.name = name;
      self.age = age;

      return self;
   }

   fun get_age(self) -> num {
      emit self.age;
   }

   fun get_name(self) -> str {
      emit self.name;
   }

   fun disp_(self) -> str {
      return f"{ name: #[self.name], age: #[self.age] }";
   }
}

fun fibb(n: num) -> num {
   if n <= 1 {
      emit n;
   } else {
      emit fibb(n - 1) + fibb(n - 2);
   }
}


#:## 

loop( <base_state>, Optional<itered_state> -> <exec_block> );


##:#


loop(0..arr.len(), i -> {});

loop(0..10, i -> {});

loop(arr.iter(), (item) -> {});

loop(true -> {});


